# Generated by Django 3.0.6 on 2020-08-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='商品库存'),
        ),
    ]
